apiVersion: v1
kind: Service
metadata:
  name: {{ include "freecinc-com.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "freecinc-com.name" . }}
    helm.sh/chart: {{ include "freecinc-com.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "freecinc-com.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

