apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "freecinc-com.fullname" . }}
  annotations:
    app.kubernetes.io/name: {{ include "freecinc-com.name" . }}
    helm.sh/chart: {{ include "freecinc-com.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    certmanager.k8s.io/issuer: {{ include "freecinc-com.fullname" . }}
    ingress.class: nginx
spec:
  rules: 
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend: 
          # this specifies the http backend; the taskd forwarding is in nginx-ingress.tcp in values.yaml.
          serviceName: {{ include "freecinc-com.fullname" . }}-backend
          servicePort: 80
  tls: # < placing a host in the TLS config will indicate a cert should be created
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ include "freecinc-com.fullname" . }}-tls
