apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pki
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-pki
    helm.sh/chart: {{ include "freecinc-com.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
