apiVersion: v1
kind: Service
metadata:
  name: {{ include "freecinc-com.fullname" . }}-extservice
  labels:
    app.kubernetes.io/name: {{ include "freecinc-com.name" . }}
    helm.sh/chart: {{ include "freecinc-com.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: taskd
      port: 53589
      targetPort: 53589
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "freecinc-com.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
