webImage:
  repository: djmitche/freecinc-web
  tag: ca3c366
  pullPolicy: IfNotPresent

taskdImage:
  repository: djmitche/freecinc-taskd
  tag: d3c62b0
  pullPolicy: IfNotPresent

# the contact email for certificate issuance
certContactEmail: nobody@v.igoro.us

nginx-ingress:
  rbac:
    create: true
  serviceAccount:
    create: true
  # forward the taskd port
  tcp:
    53589: default/dev-freecinc-com-backend:53589
