webImage:
  repository: djmitche/freecinc-web
  tag: 4438e84
  pullPolicy: IfNotPresent

taskdImage:
  repository: djmitche/freecinc-taskd
  tag: 9f05c1b
  pullPolicy: IfNotPresent

ingress-controller:
  rbac:
    create: true
  serviceAccount:
    create: true
  # forward the taskd port
  tcp:
    53589: default/dev-freecinc-com-backend:53589
